### ISSUE TITLE
streamVideoStorageInfo API an't use

### ISSUE THREAD

**Issue by espoir1989** [stratosnet/sds#136]
[DEBUG]2022/03/12 16:10:48 query_file_info.go:28: path: sdm://st1skzvc2jnajfmth9rsxyj78z7k76r96saa22ym5/v05ahm570r2f4cnkct7qnms6hir3fn08ie86keko
[DEBUG]2022/03/12 16:10:48 setting.go:181: GetSign ==  983e907b2ce569c669df895435c5b4592ef0ff309ffbb97943dae22116d34649c5720fb696f72ae38c2a4cf7f9f1b6670c7e7ed413677d3ad5afb00876d6340b
[DEBUG]2022/03/12 16:10:51 heart.go:118: this is a client conn,  65.108.104.49:20061
[DEBUG]2022/03/12 16:10:51 heart.go:133: not sending regular heartbeat to PP node(65.108.104.49:20061)
[INFO]2022/03/12 16:10:52 query_file_info.go:138: get，RspFileStorageInfo
[DEBUG]2022/03/12 16:10:52 requests.go:653: Received message type = *protos.RspFileStorageInfo msgBuf len = 556
[DEBUG]2022/03/12 16:10:52 requests.go:659: target =  p2p_address:"stsdsp2p1zrtrtg8t0kh26eh6py8clgmxdt9dkxe5pfehpk" wallet_address:"st1skzvc2jnajfmth9rsxyj78z7k76r96saa22ym5" slice_info:{slice_storage_info:{slice_size:4304527 slice_hash:"v05ahm57ledd49ik813latbrt5f0ttp82egst7io"} slice_number:1 storage_pp_info:{p2p_address:"stsdsp2p1a9kxrzdml5kdfgp4hj3ktmrk743kawxsykheuy" network_address:"134.195.198.32:10239" rest_address:"134.195.198.32:"} visit_result:true task_id:"12193266b3a7d77510f4f1d50e39d1c3e3d40477ee68f9773de5da646089e7f3" slice_offset:{slice_offset_end:4304527}} file_hash:"v05ahm570r2f4cnkct7qnms6hir3fn08ie86keko" file_name:"video_2022-02-03_19-18-30.mp4" result:{} req_id:"e4ec2b66-d56f-4d00-b549-69a83da34529" save_path:"./videos" file_size:4304527 is_video_stream:true sign:"=\xbe\xcb\x0c<\x12\x8b\xb0DN\x9a,,3c\x873\xe4κ\xfc\x00_\xb2\xa5\xac\xe3\xf2\xa8\xe3\xf8P}SP]'$(\x03\xeb\x10*=W+#6\xe9\xa7b\xebX\x08\xe0>K\xff\x8a\x95\xac\xcf\xff\n" sp_p2p_address:"stsdsp2p1nds6cwl67pp7w4sa5ng5c4a5af9hsjkn0xn875"
[DEBUG]2022/03/12 16:10:52 query_file_info.go:141: file hash v05ahm570r2f4cnkct7qnms6hir3fn08ie86keko
[INFO]2022/03/12 16:10:52 query_file_info.go:143: download starts:
[DEBUG]2022/03/12 16:10:53 stream_video.go:62: Received file storage info from sp  p2p_address:"stsdsp2p1zrtrtg8t0kh26eh6py8clgmxdt9dkxe5pfehpk" wallet_address:"st1skzvc2jnajfmth9rsxyj78z7k76r96saa22ym5" slice_info:{slice_storage_info:{slice_size:4304527 slice_hash:"v05ahm57ledd49ik813latbrt5f0ttp82egst7io"} slice_number:1 storage_pp_info:{p2p_address:"stsdsp2p1a9kxrzdml5kdfgp4hj3ktmrk743kawxsykheuy" network_address:"134.195.198.32:10239" rest_address:"134.195.198.32:"} visit_result:true task_id:"12193266b3a7d77510f4f1d50e39d1c3e3d40477ee68f9773de5da646089e7f3" slice_offset:{slice_offset_end:4304527}} file_hash:"v05ahm570r2f4cnkct7qnms6hir3fn08ie86keko" file_name:"video_2022-02-03_19-18-30.mp4" result:{} req_id:"e4ec2b66-d56f-4d00-b549-69a83da34529" save_path:"./videos" file_size:4304527 is_video_stream:true sign:"=\xbe\xcb\x0c<\x12\x8b\xb0DN\x9a,,3c\x873\xe4κ\xfc\x00_\xb2\xa5\xac\xe3\xf2\xa8\xe3\xf8P}SP]'$(\x03\xeb\x10*=W+#6\xe9\xa7b\xebX\x08\xe0>K\xff\x8a\x95\xac\xcf\xff\n" sp_p2p_address:"stsdsp2p1nds6cwl67pp7w4sa5ng5c4a5af9hsjkn0xn875"
[DEBUG]2022/03/12 16:10:53 file.go:242: CheckSliceExisting sliceHash v05ahm57ledd49ik813latbrt5f0ttp82egst7io
[ERROR]2022/03/12 16:10:53 video.go:124: invalid character '\x00' looking for beginning of value
2022/03/12 16:10:53 http: panic serving 127.0.0.1:56813: runtime error: invalid memory address or nil pointer dereference
goroutine 41742 [running]:
net/http.(*conn).serve.func1()
	/usr/local/Cellar/go/1.17.8/libexec/src/net/http/server.go:1802 +0xb9
panic({0x48c8a60, 0x5288cf0})
	/usr/local/Cellar/go/1.17.8/libexec/src/runtime/panic.go:1047 +0x266
net/http.(*timeoutHandler).ServeHTTP(0xc00012e000, {0x4c37268, 0xc000272540}, 0xc000116d00)
	/usr/local/Cellar/go/1.17.8/libexec/src/net/http/server.go:3342 +0x893
net/http.serverHandler.ServeHTTP({0xc000571f50}, {0x4c37268, 0xc000272540}, 0xc000116d00)
	/usr/local/Cellar/go/1.17.8/libexec/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc001518640, {0x4c3fe40, 0xc0002c4240})
	/usr/local/Cellar/go/1.17.8/libexec/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.17.8/libexec/src/net/http/server.go:3034 +0x4e8

**Comment by espoir1989** [comment]
url：
sdm://st1skzvc2jnajfmth9rsxyj78z7k76r96saa22ym5/v05ahm570r2f4cnkct7qnms6hir3fn08ie86keko

**Comment by mdumaisqsnetwork** [comment]
Closing for inactivity. This is likely not happening anymore, but if it does, please reopen with additional details like a description of what you were doing, instead of only a log dump
